// Playwright + WebGPU; environment options match gpu-fluid.browser.cjs.
const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:process.env.GPU_SOFTWARE_TEST==='1'?['--enable-unsafe-webgpu','--enable-features=Vulkan','--use-gl=angle','--use-angle=swiftshader','--disable-vulkan-surface','--no-sandbox']:[]});try{const p=await b.newPage({viewport:{width:1300,height:850}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await p.goto((process.env.POND_URL||'http://localhost:8005'));await p.waitForFunction(()=>['ready','error'].includes(document.documentElement.dataset.state),{}, {timeout:90000});assert.equal(await p.evaluate(()=>document.documentElement.dataset.state),'ready',await p.locator('#statusDetail').textContent());await p.locator('#play').evaluate(el=>el.click());await p.waitForFunction(()=>!gpuFluidDiagnostics().busy);assert.deepEqual((await p.evaluate(()=>gpuFluidDiagnostics())).dimensions,[7.5,5]);console.log('PASS large default and working editor');
await p.locator('[data-object="fluid"]').click();assert(await p.locator('#resolution').isVisible());await p.selectOption('#renderQuality','fast');await p.waitForTimeout(1500);console.log('TIMING',await p.evaluate(()=>gpuFluidDiagnostics()));
await p.locator('[data-object="tub"]').click();assert.equal(await p.locator('#resolution').isVisible(),false);for(const [choice,dims] of [['10,6.8',[10,6.8]],['14,10',[14,10]],['5,3.4',[5,3.4]]]){await p.selectOption('#tubPreset',choice);await p.locator('#applyTub').click();await p.waitForFunction(d=>JSON.stringify(gpuFluidDiagnostics().dimensions)===JSON.stringify(d),dims,{timeout:60000});await p.waitForFunction(()=>!gpuFluidDiagnostics().busy);const d=await p.evaluate(()=>gpuFluidDiagnostics());assert.equal(d.count,6144);assert.equal(d.running,false);const state=await p.evaluate(()=>inspectGPUFluid());assert(state.finite&&state.outside===0&&state.insideSolids===0);console.log('PASS tub',dims,'spacing',d.spacing);}
await p.locator('#tubWidth').fill('20');await p.locator('#applyTub').click();assert.match(await p.locator('#sizeHelp').textContent(),/Enter width/);assert.deepEqual((await p.evaluate(()=>gpuFluidDiagnostics())).dimensions,[5,3.4]);console.log('PASS invalid dimension rejected');
await p.locator('[data-object="duck"]').click();assert(await p.locator('#moveDuck').isVisible());await p.locator('#moveDuck').click();assert(await p.locator('[data-tool="duck"]').evaluate(el=>el.classList.contains('selected')));console.log('PASS functional object selection / inspector');
await p.setViewportSize({width:390,height:844});await p.waitForTimeout(1500);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await p.evaluate(()=>document.documentElement.scrollHeight>innerHeight),false);console.log('PASS edge-to-edge mobile split, no overflow');assert.deepEqual(errors,[]);console.log('PASS no WebGPU errors');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
