// Requires Playwright and a WebGPU-capable browser. See GPU-FLUID.md.
const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:process.env.GPU_SOFTWARE_TEST==='1'?['--enable-unsafe-webgpu','--enable-features=Vulkan','--use-gl=angle','--use-angle=swiftshader','--disable-vulkan-surface','--no-sandbox']:[]});try{const p=await b.newPage({viewport:{width:1200,height:980}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await p.goto((process.env.POND_URL||'http://localhost:8004'));await p.waitForFunction(()=>document.documentElement.dataset.state==='ready',{}, {timeout:90000});await p.waitForFunction(()=>gpuFluidDiagnostics().time>.25,{}, {timeout:90000});await p.locator('#play').evaluate(el=>el.click());await p.waitForFunction(()=>!gpuFluidDiagnostics().busy);let d=await p.evaluate(()=>gpuFluidDiagnostics());const time=d.time;await p.waitForTimeout(200);assert.equal((await p.evaluate(()=>gpuFluidDiagnostics())).time,time);console.log('PASS real WebGPU renders, fixed-step pause');
await p.locator('[data-object="fluid"]').click();await p.selectOption('#view','particles');await p.waitForTimeout(1800);assert.equal((await p.evaluate(()=>gpuFluidDiagnostics())).display,'particles');console.log('PASS particle inspection view');
await p.selectOption('#view','surface');await p.locator('[data-tool="duck"]').evaluate(el=>el.click());const box=await p.locator('#fluid').boundingBox();await p.mouse.click(box.x+box.width*.4,box.y+box.height*.6);await p.locator('#play').evaluate(el=>el.click());await p.waitForFunction(()=>gpuFluidDiagnostics().time>0.40,{}, {timeout:90000});await p.locator('#play').evaluate(el=>el.click());await p.waitForFunction(()=>!gpuFluidDiagnostics().busy);let moved=await p.evaluate(()=>gpuFluidDiagnostics());assert(Math.hypot(moved.body[0]-.9,moved.body[2]-.25)>.01);console.log('PASS duck moves as a kinematic solid');let read=await p.evaluate(()=>inspectGPUFluid());assert(read.finite&&read.outside===0&&read.insideSolids===0);console.log('PASS GPU readback: no escaped or solid-penetrating particles',read);
await p.locator('#reset').evaluate(el=>el.click());await p.waitForFunction(()=>gpuFluidDiagnostics().time===0);await p.selectOption('#resolution','12000');await p.waitForFunction(()=>gpuFluidDiagnostics().count===12000,{}, {timeout:60000});await p.waitForFunction(()=>!gpuFluidDiagnostics().busy);assert.equal((await p.evaluate(()=>gpuFluidDiagnostics())).running,false);console.log('PASS reset/resolution preserve pause and rebuild GPU buffers');
await p.setViewportSize({width:390,height:844});await p.waitForTimeout(1200);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);console.log('PASS mobile layout');assert.deepEqual(errors,[]);console.log('PASS no GPU validation/runtime errors');
const q=await b.newPage();await q.addInitScript(()=>Object.defineProperty(navigator,'gpu',{value:undefined}));await q.goto((process.env.POND_URL||'http://localhost:8004'));await q.waitForFunction(()=>document.documentElement.dataset.state==='error');assert.match(await q.locator('#statusDetail').textContent(),/does not expose WebGPU/);console.log('PASS unsupported browser shows actionable error, no CPU substitution');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
