//============================================================================================================================================
// 📦 Project-Zero/Source/GameExecution.cpp — Celestial Frame Entry Point (Lens Flare + Clouds)
//============================================================================================================================================
//
//    Project Zero renders one frame in which the whole celestial port is live at once: atmosphere, sun, sky,
//    twilight, stars, moons, the cloud layer, the volumetric cloud deck, the local cloud volume, both fogs,
//    wind, precipitation, the rainbow, THE LENS FLARE and the tonemap chain.
//
//    The flare and the clouds are not re-implemented here. They are `CelestialIntegrator::LensFlare`,
//    `CloudSlab`, `CloudMarch` and `MarchLocalVolumes` — the reference celestial console's own `lensFlare()`,
//    `cloudLayer()`, `cloudMarch()` and `marchLocal()`, transcribed expression for expression. This file only
//    chooses the viewpoint, the time of day and the flare variety, then asks the stage for a frame.
//
//    ⚠️ The sun is deliberately placed just inside the frame edge. A flare is only observable when the solar
//    disc is actually on screen and in front of the camera: `AddLensFlare` gates on `InFront`, on the sun's
//    elevation and on `InFrame`, so a sun behind the observer correctly produces nothing. Renders are emitted
//    for all four varieties the panel exposes, because "the flare is broken" is otherwise an opinion rather
//    than four images a reader can compare.
//
//============================================================================================================================================

#include "CelestialStage.h"
#include "FlyThroughSolver.h"
#include "../../../DeviceExchange/DiagnosticMetrics.h"

#include <array>
#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <string>

namespace {

constexpr uint32_t kViewportWidth  = 960u;
constexpr uint32_t kViewportHeight = 540u;

//    The four varieties `pp_flareType` exposes, in the panel's own order. `FlareVariety` is compared against
//    exact float literals inside the reference kernel, so these must stay whole numbers.
struct FlareVariant
{
    const char* Name;
    float       Variety;
};

constexpr std::array<FlareVariant, 4> kFlareVarieties{ {
    { "Cinematic",  0.0f },
    { "Anamorphic", 1.0f },
    { "Starburst",  2.0f },
    { "Halo",       3.0f },
} };

//    Convert a rendered PPM to PNG when the helper and Pillow are both available. The PPM is the real output;
//    the PNG is a convenience for viewing, so a missing converter is reported and never fatal.
void ConvertToPng(const std::string& PpmPath, const std::string& PngPath) noexcept
{
    const std::string Command = "python3 ../../Tools/PpmToPng.py \"" + PpmPath + "\" \"" + PngPath + "\" > /dev/null 2>&1";
    if (std::system(Command.c_str()) == 0)
    {
        std::cout << "                    → " << PngPath << "\n";
    }
}

//    Sample the shipping flare kernel across a grid and write the results out, so `CheckLensFlare.py` can hold
//    them against its own independent transcription of the reference `lensFlare()` GLSL. This is what keeps the
//    port honest: the images prove the flare is composited, and this proves it is still the REFERENCE flare.
//
//    The kernel is private, so it is exercised the way a frame exercises it — through `AddLensFlare` on a black
//    radiance, which returns exactly `LensFlare(...) * SunIntensity * 0.09 * SunColour`. Dividing that scale
//    back out recovers the raw kernel value.
void DumpFlareKernel(const std::string& OutputPath) noexcept
{
    std::FILE* Out = std::fopen(OutputPath.c_str(), "w");
    if (Out == nullptr)
    {
        return;
    }

    std::fprintf(Out, "# variety ghosts halo streak chroma intensity  u v sunU sunV visibility  r g b\n");
    std::fprintf(Out, "# generated by Project-Zero; checked against the reference lensFlare() by CheckLensFlare.py\n");

    for (const FlareVariant& Variant : kFlareVarieties)
    {
        Frontier::ProjectZero::CelestialCriteria Criteria{};
        Criteria.Sun.LocalHours           = 12.0f;          // high sun: a clean, fully visible gate
        Criteria.Sun.ColourTemperature    = 6500.0f;
        Criteria.Post.FlareOn             = true;
        Criteria.Post.FlareVariety        = Variant.Variety;
        Criteria.Post.FlareIntensity      = 1.0f;
        Criteria.Post.Ghosts              = 5.0f;
        Criteria.Post.Halo                = 0.55f;
        Criteria.Post.Streak              = 0.8f;
        Criteria.Post.Chroma              = 0.65f;

        Frontier::ProjectZero::CelestialIntegrator Integrator(Criteria);
        Integrator.SolveFrame(1.5f);

        //    An observer looking straight at the sun, so the disc lands at screen centre and the visibility
        //    gate opens fully. The basis is built from the solved sun direction rather than assumed.
        const Frontier::Vector3 SunDirection = Integrator.QueryFrame().SunDirection;
        Frontier::ProjectZero::ObserverFrame Observer{};
        Observer.Position    = Frontier::Vector3{ 0.0f, 2.0f, 0.0f };
        Observer.Forward     = SunDirection;
        Observer.Right       = Frontier::Vector3{ SunDirection.z, 0.0f, -SunDirection.x }.Normalized();
        Observer.Upward      = Frontier::ProjectZero::Cross(Observer.Right, Observer.Forward).Normalized();
        Observer.TangentHalf = std::tan(0.5f * 72.0f * 3.14159265f / 180.0f);
        Observer.Height      = 2.0f;

        //    Recover the constant `AddLensFlare` multiplies the kernel by.
        const Frontier::Vector3 SunColour = Integrator.QueryFrame().SunColour;
        const float Scale = Criteria.Sun.Intensity * 0.09f;

        //    The gate `AddLensFlare` applies, restated so the dumped visibility matches what it used.
        const float Elevation   = Integrator.QueryFrame().SunElevationDeg;
        const float SunUp       = Frontier::ProjectZero::SmoothStep(-6.0f, 4.0f, Elevation);
        const float Visibility  = 1.0f * SunUp * 1.0f * Frontier::ProjectZero::Step(0.0f, Elevation + 0.5f);

        for (int iy = -4; iy <= 4; ++iy)
        {
            for (int ix = -6; ix <= 6; ++ix)
            {
                const float u = static_cast<float>(ix) * 0.22f;
                const float v = static_cast<float>(iy) * 0.22f;

                const Frontier::Vector3 Value =
                    Integrator.AddLensFlare(Frontier::Vector3{ 0.0f, 0.0f, 0.0f }, u, v, Observer);

                //    Undo the sun colour and intensity so what is written is the bare kernel.
                const auto Undo = [&](float Component, float Channel) -> float
                {
                    const float Divisor = Scale * Channel;
                    return (std::abs(Divisor) > 1e-8f) ? (Component / Divisor) : 0.0f;
                };

                std::fprintf(Out, "%.1f %.1f %.6f %.6f %.6f %.6f  %.6f %.6f %.6f %.6f %.6f  %.8f %.8f %.8f\n",
                             Variant.Variety, Criteria.Post.Ghosts, Criteria.Post.Halo,
                             Criteria.Post.Streak, Criteria.Post.Chroma, Criteria.Post.FlareIntensity,
                             u, v, 0.0f, 0.0f, Visibility,
                             Undo(Value.x, SunColour.x), Undo(Value.y, SunColour.y), Undo(Value.z, SunColour.z));
            }
        }
    }

    std::fclose(Out);
}

} // namespace

int main(int ArgumentCount, char** ArgumentValues)
{
    (void)ArgumentCount;
    (void)ArgumentValues;

    std::cout << "================================================================================\n";
    std::cout << "            PROJECT-ZERO — CELESTIAL FRAME (LENS FLARE + CLOUDS)                \n";
    std::cout << "================================================================================\n";

    Frontier::DiagnosticConfiguration ReportConfig{};
    ReportConfig.DestinationFolder          = "Diagnostics";
    ReportConfig.OutputFileStem             = "ProjectZero_TelemetryReport";
    ReportConfig.FileExtension              = ".md";
    ReportConfig.TimestampPrefixEnabled     = true;
    ReportConfig.ConsoleEchoEnabled         = false;
    ReportConfig.MarkdownTableFormatEnabled = true;

    Frontier::DiagnosticMetrics ReportLogger(ReportConfig);
    if (ReportLogger.InitializeSink())
    {
        ReportLogger.RecordMessage(Frontier::DiagnosticSeverity::Information, "Bootstrap",
                                   "Project-Zero celestial stage initialised.");
    }

    //------------------------------------------------------------------------------------------------------
    //    The sky. Defaults are the reference panel's own `defaults()`; only the framing is chosen here.
    //------------------------------------------------------------------------------------------------------

    Frontier::ProjectZero::CelestialCriteria SkyCriteria{};

    //    Morning sun, low enough to throw a long flare and to light the cloud deck from the side.
    //
    //    ⚠️ The azimuth offset is not cosmetic. At 07:36 the solved sun sits at world bearing +79°, which from
    //    inside the room is behind the green wall — `AddLensFlare` would correctly gate itself off and the
    //    frame would show no flare at all. Swinging the azimuth by −79° puts the disc on the +Y axis, straight
    //    out through the window, which is the only bearing where the room can see it.
    SkyCriteria.Sun.LocalHours            = 7.6f;
    SkyCriteria.Sun.AzimuthOffsetDegrees  = -79.0f;
    SkyCriteria.Observer.Height           = 1.7f;

    //    Clouds — the note says the deck is right, so it keeps the reference's values and is simply switched
    //    on. `CloudLayer` is the thin slab (`cloudLayer()`); `VolumetricCloud` is the ray-marched deck
    //    (`cloudMarch()`); `LocalCloud` is the single placed cumulus (`marchLocal()`).
    SkyCriteria.CloudLayer.Visible        = true;
    SkyCriteria.VolumetricCloud.Visible   = true;
    SkyCriteria.VolumetricCloud.Coverage  = 0.52f;
    SkyCriteria.LocalCloud.Placement      = Frontier::Vector3{ 120.0f, 260.0f, -420.0f };
    SkyCriteria.LocalCloud.HalfExtents    = Frontier::Vector3{ 180.0f, 70.0f, 140.0f };

    //    Rain off: this frame is about the flare and the cloud deck, and 25 000 streaks over the sun only
    //    makes the comparison harder to read.
    SkyCriteria.Precipitation.Visible     = false;

    //    The flare itself — the reference defaults, stated explicitly because they are the subject.
    SkyCriteria.Post.FlareOn              = true;
    SkyCriteria.Post.FlareIntensity       = 1.0f;
    SkyCriteria.Post.Ghosts               = 5.0f;
    SkyCriteria.Post.Halo                 = 0.55f;
    SkyCriteria.Post.Streak               = 0.8f;
    SkyCriteria.Post.Chroma               = 0.65f;

    //------------------------------------------------------------------------------------------------------
    //    The stage. No Cornell box here — the open sky is the subject, so the room is left closed off and the
    //    frame is all sky, cloud and ground.
    //------------------------------------------------------------------------------------------------------

    Frontier::ProjectZero::CelestialStageCriteria StageCriteria{};
    StageCriteria.Width             = kViewportWidth;
    StageCriteria.Height            = kViewportHeight;
    StageCriteria.SampleCount       = 2u;
    StageCriteria.IndirectRays      = 4u;
    StageCriteria.SpatialPasses     = 1u;
    StageCriteria.SkyTaps           = 12u;
    StageCriteria.OpenCeiling       = true;
    StageCriteria.OpenWall          = true;
    StageCriteria.SkyLighting       = true;
    StageCriteria.EmissiveLuminaire = false;

    Frontier::ProjectZero::CelestialStage Stage(StageCriteria, SkyCriteria);

    //    Settle the weather so the cloud advection and the wind integral are not at t=0.
    for (int Tick = 0; Tick < 45; ++Tick)
    {
        Stage.Advance(1.0f / 30.0f);
    }

    //------------------------------------------------------------------------------------------------------
    //    The camera. Yawed onto the morning sun and pitched up a little, so the disc sits high-right of centre
    //    with the cloud deck beneath it — the arrangement that puts ghosts, halo, streak and burst all in frame.
    //------------------------------------------------------------------------------------------------------

    Frontier::ProjectZero::FlyThroughConfiguration FlightConfig{};
    FlightConfig.BaseFlightSpeed      = 8.0f;
    FlightConfig.BoostMultiplier      = 4.0f;
    FlightConfig.MouseSensitivity     = 0.0025f;
    FlightConfig.ScrollSpeedIncrement = 1.0f;
    FlightConfig.AccelerationDamping  = 0.85f;

    const float AspectRatio = static_cast<float>(kViewportWidth) / static_cast<float>(kViewportHeight);

    //    World is +X right, +Y forward, +Z up; the room spans X[-1,1], Y[0,2], Z[0,2.4] and the window is cut
    //    in the far wall at Y=2. Standing back at Y=-1.4 and looking straight down +Y puts the whole opening
    //    in shot, and a +16° pitch raises the sun (elevation 21.4°) clear of the lintel.
    Frontier::ProjectZero::FlyThroughSolver Camera(FlightConfig);
    Camera.AssignSpatialLocation(Frontier::Vector3{ 0.0f, -1.4f, 1.2f });
    Camera.AssignOrientationEuler(16.0f * 3.14159265f / 180.0f, 0.0f, 0.0f);
    Camera.AssignFieldOfView(72.0f);
    Camera.AssignAspectRatio(AspectRatio);

    const auto& Frame = Stage.QuerySky().QueryFrame();
    std::cout << "[Project-Zero] Sun elevation " << Frame.SunElevationDeg << " deg"
              << " | local hours " << SkyCriteria.Sun.LocalHours << "\n";
    std::cout << "[Project-Zero] Rendering " << kViewportWidth << "x" << kViewportHeight
              << " — atmosphere, cloud layer, volumetric deck, local cloud, lens flare, tonemap.\n\n";

    //------------------------------------------------------------------------------------------------------
    //    One frame per flare variety, plus a flare-off control. The control is what makes the other four
    //    provable: if "flare on" and "flare off" are the same image, the flare is not being composited.
    //------------------------------------------------------------------------------------------------------

    double ReferenceLuminance = 0.0;

    for (const FlareVariant& Variant : kFlareVarieties)
    {
        Stage.MutableSky().MutableCriteria().Post.FlareOn      = true;
        Stage.MutableSky().MutableCriteria().Post.FlareVariety = Variant.Variety;

        const auto Started = std::chrono::steady_clock::now();
        Stage.RenderFrame(Camera);
        const auto Elapsed = std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - Started).count();

        const auto& Statistics = Stage.QueryStatistics();
        const std::string Stem = std::string("Diagnostics/ProjectZero_Flare_") + Variant.Name;

        std::cout << "  " << Variant.Name
                  << "  mean L " << Statistics.MeanLuminance
                  << " | sky " << (Statistics.SkyPixelFraction * 100.0) << "%"
                  << " | colours " << Statistics.DistinctColours
                  << " | " << Elapsed << " ms\n";

        if (Stage.ExportPpmImage(Stem + ".ppm"))
        {
            ConvertToPng(Stem + ".ppm", Stem + ".png");
        }

        ReportLogger.RecordMeasurement(std::string("Flare_") + Variant.Name + "_MeanLuminance",
                                       Statistics.MeanLuminance, "cd/m2");

        if (Variant.Variety == 0.0f)
        {
            ReferenceLuminance = Statistics.MeanLuminance;
        }
    }

    //    The negative control.
    Stage.MutableSky().MutableCriteria().Post.FlareOn = false;
    Stage.RenderFrame(Camera);
    const double FlareOffLuminance = Stage.QueryStatistics().MeanLuminance;
    if (Stage.ExportPpmImage("Diagnostics/ProjectZero_Flare_Off.ppm"))
    {
        ConvertToPng("Diagnostics/ProjectZero_Flare_Off.ppm", "Diagnostics/ProjectZero_Flare_Off.png");
    }

    std::cout << "\n  Flare off (control)  mean L " << FlareOffLuminance << "\n";
    std::cout << "  Cinematic − control  ΔL = " << (ReferenceLuminance - FlareOffLuminance)
              << "  (must be > 0 — the flare adds light)\n";

    ReportLogger.RecordMeasurement("Flare_Off_MeanLuminance", FlareOffLuminance, "cd/m2");
    //    Dump the kernel so the fidelity gate can hold it against the reference GLSL.
    DumpFlareKernel("Diagnostics/FlareKernelDump.txt");
    std::cout << "  Kernel samples → Diagnostics/FlareKernelDump.txt\n";

    ReportLogger.RecordMessage(Frontier::DiagnosticSeverity::Information, "Celestial",
                               "Rendered the celestial frame for all four flare varieties and the off control.");
    ReportLogger.FlushSink();

    std::cout << "\n[Project-Zero] Done. Frames in Projects/Project-Zero/Diagnostics/.\n";
    return 0;
}
