import { EMITTER_KIND } from './volumetric/EmitterSystem.js';

/**
 * Look-and-feel presets.
 *
 * A preset is a bundle of solver parameters, renderer parameters, camera framing
 * and an emitter schedule. `emitters` is called on apply and `tick` every frame
 * (used for continuous/pulsing sources).
 */
export const PRESETS = {
  campfire: {
    label: 'Campfire',
    blurb: 'Sustained flame with soot and smoke drift',
    solver: {
      buoyancy: 9.5,
      smokeBuoyancy: 0.9,
      ambientCooling: 1.0,
      turbulence: 1.3,
      vorticity: 3.6,
      velocityDamping: 0.05,
      dissipation: 0.028,
      fuelBurnRate: 4.2,
      ignitionTemp: 0.38,
      heatOfCombustion: 2.6,
      sootYield: 0.30,
      emberGain: 0.55,
      emberDecay: 1.4,
      thermalExpansion: 6.0,
      swirlScale: 0.34,
      swirlSpeed: 0.4,
      wind: [0.12, 0, 0.05],
      windResponse: 0.16,
      obstacle: { mode: 0, center: [0, 1, 0], halfExtents: [0.2, 0.2, 0.2], radius: 0 },
    },
    render: {
      extinction: 2.1,
      emission: 40,
      flameScale: 1.05,
      smokeAlbedo: 0.85,
      shadowTaps: 2,
      exposure: 0.15,
      fireLightIntensity: 2.2,
      fireLightColor: [1.0, 0.5, 0.18],
    },
    camera: { target: [0, 1.5, 0], distance: 6.2, yaw: 0.7, pitch: 0.16, fov: 42 },
    emitters(system) {
      system.clear();
      system.add({
        kind: EMITTER_KIND.fire,
        position: [0, 0.55, 0],
        radius: 0.5,
        size: [0.42, 0.62, 0.42],
        velocity: [0, 2.1, 0],
        densityRate: 0.16,
        temperatureRate: 2.6,
        fuelRate: 1.6,
        emberRate: 0.5,
        color: [1.0, 0.55, 0.2],
        softness: 0.25,
        flicker: 0.5,
        swirl: 0.55,
        life: Infinity,
      });
      system.add({
        kind: EMITTER_KIND.smoke,
        position: [0, 0.6, 0],
        radius: 0.7,
        size: [0.6, 0.9, 0.6],
        velocity: [0.1, 1.2, 0.05],
        densityRate: 0.22,
        temperatureRate: 0.25,
        color: [0.35, 0.34, 0.36],
        softness: 0.4,
        flicker: 0.25,
        swirl: 0.3,
        life: Infinity,
      });
    },
  },

  smoke: {
    label: 'Smoke plume',
    blurb: 'Cold colored smoke, wind shear and heavy turbulence',
    solver: {
      buoyancy: 3.0,
      smokeBuoyancy: 1.6,
      ambientCooling: 1.6,
      turbulence: 2.3,
      vorticity: 4.6,
      velocityDamping: 0.04,
      dissipation: 0.016,
      fuelBurnRate: 1.0,
      ignitionTemp: 1.5,
      heatOfCombustion: 0.8,
      sootYield: 0.1,
      thermalExpansion: 2.0,
      swirlScale: 0.28,
      swirlSpeed: 0.32,
      wind: [0.55, 0, 0.18],
      windResponse: 0.5,
    },
    render: {
      extinction: 1.7,
      emission: 20,
      flameScale: 0.5,
      smokeAlbedo: 1.05,
      shadowTaps: 2,
      exposure: 0.35,
      skyZenith: [0.07, 0.09, 0.14],
      fireLightIntensity: 0.6,
    },
    camera: { target: [0, 2.1, 0], distance: 7.0, yaw: 0.5, pitch: 0.12, fov: 45 },
    emitters(system) {
      system.clear();
      system.add({
        kind: EMITTER_KIND.smoke,
        position: [0, 0.5, 0],
        radius: 0.55,
        size: [0.45, 0.45, 0.45],
        velocity: [1.1, 1.9, 0.3],
        densityRate: 1.5,
        temperatureRate: 0.35,
        color: [0.75, 0.78, 0.85],
        softness: 0.35,
        flicker: 0.2,
        swirl: 0.9,
        life: Infinity,
      });
    },
  },

  explosion: {
    label: 'Explosion',
    blurb: 'One-shot detonation: fireball, blast ring, rolling smoke',
    solver: {
      buoyancy: 11.0,
      smokeBuoyancy: 1.1,
      ambientCooling: 0.85,
      turbulence: 3.0,
      vorticity: 5.5,
      velocityDamping: 0.045,
      dissipation: 0.02,
      fuelBurnRate: 2.4,
      ignitionTemp: 0.16,
      heatOfCombustion: 3.3,
      sootYield: 0.62,
      emberGain: 0.85,
      emberDecay: 0.85,
      thermalExpansion: 17.0,
      maxSpeed: 20,
      swirlScale: 0.24,
      swirlSpeed: 0.45,
      wind: [0.05, 0, 0.02],
      windResponse: 0.1,
    },
    render: {
      extinction: 2.4,
      emission: 52,
      flameScale: 0.85,
      smokeAlbedo: 0.8,
      shadowTaps: 3,
      exposure: 0.05,
      fireLightIntensity: 8.0,
      fireLightColor: [1.0, 0.52, 0.16],
    },
    camera: { target: [0, 1.9, 0], distance: 8.4, yaw: 0.75, pitch: 0.14, fov: 46 },
    emitters(system) {
      system.clear();
      // sustained sparks/dust after the blast so the scene keeps living
      system.add({
        kind: EMITTER_KIND.debris,
        position: [0, 0.35, 0],
        radius: 0.85,
        size: [1.1, 0.28, 1.1],
        velocity: [0, 0.55, 0],
        densityRate: 0.55,
        temperatureRate: 0.35,
        color: [0.42, 0.38, 0.34],
        softness: 0.55,
        flicker: 0.3,
        swirl: 0.7,
        life: Infinity,
      });
    },
    detonate(ctx) {
      const center = (ctx && ctx.center) || [0, 1.55, 0];
      const power = (ctx && ctx.power) ?? 1.0;
      return [
        {
          kind: EMITTER_KIND.explosion,
          position: center,
          radius: 0.62 * power,
          size: [0.6, 0.55, 0.6],
          velocity: [0, 1.4, 0],
          densityRate: 0.5 * power,
          temperatureRate: 7.5 * power,
          fuelRate: 5.2 * power,
          emberRate: 2.4 * power,
          color: [1.0, 0.5, 0.15],
          softness: 0.55,
          flicker: 0.85,
          swirl: 1.4,
          life: 0.38,
          fadeIn: 0.03,
          fadeOut: 0.5,
        },
        {
          kind: EMITTER_KIND.debris,
          position: [center[0], 0.3, center[2]],
          radius: 1.0 * power,
          size: [1.0, 0.35, 1.0],
          velocity: [0, 0.9, 0],
          densityRate: 2.6 * power,
          temperatureRate: 0.5,
          color: [0.5, 0.44, 0.38],
          softness: 0.6,
          flicker: 0.4,
          swirl: 0.9,
          life: 1.4,
          fadeOut: 0.6,
        },
      ];
    },
  },

  inferno: {
    label: 'Inferno',
    blurb: 'Large scale fire storm with heavy soot production',
    solver: {
      buoyancy: 12.0,
      smokeBuoyancy: 1.4,
      ambientCooling: 0.7,
      turbulence: 3.6,
      vorticity: 6.0,
      velocityDamping: 0.04,
      dissipation: 0.014,
      fuelBurnRate: 2.0,
      ignitionTemp: 0.12,
      heatOfCombustion: 3.6,
      sootYield: 0.75,
      emberGain: 1.0,
      emberDecay: 0.9,
      thermalExpansion: 9.0,
      maxSpeed: 18,
      swirlScale: 0.2,
      swirlSpeed: 0.5,
      wind: [0.22, 0, 0.1],
      windResponse: 0.18,
      obstacle: { mode: 1, center: [1.25, 0.7, 0.15], halfExtents: [0.3, 0.7, 0.85], radius: 0 },
    },
    render: {
      extinction: 2.6,
      emission: 55,
      flameScale: 0.9,
      smokeAlbedo: 0.75,
      shadowTaps: 3,
      exposure: 0.0,
      fireLightIntensity: 6.0,
    },
    camera: { target: [0, 2.2, 0], distance: 9.5, yaw: 0.55, pitch: 0.18, fov: 48 },
    emitters(system) {
      system.clear();
      system.add({
        kind: EMITTER_KIND.fire,
        position: [0, 0.6, 0],
        radius: 0.8,
        size: [0.9, 0.5, 0.9],
        velocity: [0, 3.0, 0],
        densityRate: 0.4,
        temperatureRate: 4.0,
        fuelRate: 2.6,
        emberRate: 1.0,
        color: [1.0, 0.48, 0.14],
        softness: 0.4,
        flicker: 0.7,
        swirl: 1.1,
        life: Infinity,
      });
      system.add({
        kind: EMITTER_KIND.fire,
        position: [0.45, 0.55, 0.3],
        radius: 0.45,
        size: [0.5, 0.42, 0.5],
        velocity: [0.2, 2.6, 0.1],
        densityRate: 0.3,
        temperatureRate: 3.2,
        fuelRate: 2.0,
        emberRate: 0.8,
        softness: 0.5,
        flicker: 0.9,
        swirl: 1.4,
        life: Infinity,
      });
      system.add({
        kind: EMITTER_KIND.smoke,
        position: [-0.3, 1.1, -0.2],
        radius: 1.1,
        size: [1.2, 1.0, 1.2],
        velocity: [0.1, 2.2, 0.05],
        densityRate: 0.6,
        temperatureRate: 1.2,
        color: [0.22, 0.2, 0.2],
        softness: 0.6,
        flicker: 0.35,
        swirl: 0.8,
        life: Infinity,
      });
    },
  },

  jet: {
    label: 'Jet blast',
    blurb: 'High-velocity exhaust impinging on the ground',
    solver: {
      buoyancy: 5.0,
      smokeBuoyancy: 0.8,
      ambientCooling: 1.3,
      turbulence: 2.0,
      vorticity: 4.0,
      velocityDamping: 0.05,
      dissipation: 0.02,
      fuelBurnRate: 3.0,
      ignitionTemp: 0.5,
      heatOfCombustion: 1.6,
      sootYield: 0.22,
      emberGain: 0.3,
      thermalExpansion: 4.0,
      maxSpeed: 22,
      swirlScale: 0.3,
      swirlSpeed: 0.4,
      wind: [0.0, 0, 0.0],
      windResponse: 0.08,
    },
    render: {
      extinction: 2.0,
      emission: 34,
      flameScale: 0.75,
      smokeAlbedo: 0.95,
      shadowTaps: 2,
      exposure: 0.2,
      fireLightIntensity: 3.0,
    },
    camera: { target: [0, 1.5, 0], distance: 7.6, yaw: 0.9, pitch: 0.1, fov: 45 },
    emitters(system) {
      system.clear();
      system.add({
        kind: EMITTER_KIND.fire,
        position: [0, 3.1, 0],
        radius: 0.42,
        size: [0.34, 0.3, 0.34],
        velocity: [0, -13.5, 0],
        densityRate: 1.1,
        temperatureRate: 3.6,
        fuelRate: 0.9,
        emberRate: 0.4,
        color: [1.0, 0.62, 0.28],
        softness: 0.2,
        flicker: 0.35,
        swirl: 0.9,
        life: Infinity,
      });
      system.add({
        kind: EMITTER_KIND.smoke,
        position: [0, 2.9, 0],
        radius: 0.5,
        size: [0.4, 0.34, 0.4],
        velocity: [0, -10.0, 0],
        densityRate: 0.7,
        color: [0.5, 0.5, 0.55],
        softness: 0.3,
        flicker: 0.2,
        swirl: 0.5,
        life: Infinity,
      });
    },
  },

  candle: {
    label: 'Candle',
    blurb: 'Small laminar flame - good for close-up detail checks',
    solver: {
      buoyancy: 7.0,
      smokeBuoyancy: 0.6,
      ambientCooling: 1.4,
      turbulence: 0.7,
      vorticity: 2.2,
      velocityDamping: 0.08,
      dissipation: 0.05,
      fuelBurnRate: 5.0,
      ignitionTemp: 0.3,
      heatOfCombustion: 2.2,
      sootYield: 0.14,
      emberGain: 0.3,
      thermalExpansion: 2.5,
      swirlScale: 0.5,
      swirlSpeed: 0.5,
      wind: [0, 0, 0],
      windResponse: 0.05,
    },
    render: {
      extinction: 2.6,
      emission: 46,
      flameScale: 1.2,
      smokeAlbedo: 0.8,
      shadowTaps: 2,
      exposure: 0.6,
      fireLightIntensity: 1.0,
    },
    camera: { target: [0, 1.1, 0], distance: 3.4, yaw: 0.6, pitch: 0.05, fov: 38 },
    emitters(system) {
      system.clear();
      system.add({
        kind: EMITTER_KIND.fire,
        position: [0, 0.62, 0],
        radius: 0.26,
        size: [0.16, 0.34, 0.16],
        velocity: [0, 1.15, 0],
        densityRate: 0.06,
        temperatureRate: 2.9,
        fuelRate: 1.35,
        emberRate: 0.16,
        color: [1.0, 0.62, 0.25],
        softness: 0.3,
        flicker: 0.28,
        swirl: 0.22,
        life: Infinity,
      });
    },
  },
};

export const PRESET_ORDER = ['campfire', 'explosion', 'inferno', 'smoke', 'jet', 'candle'];

export const QUALITY = {
  low: {
    label: 'Low',
    resolution: 64,
    pressureIterations: 16,
    substeps: 1,
    steps: 56,
    shadowTaps: 0,
    renderScale: 0.7,
  },
  medium: {
    label: 'Medium',
    resolution: 96,
    pressureIterations: 22,
    substeps: 1,
    steps: 80,
    shadowTaps: 2,
    renderScale: 0.85,
  },
  high: {
    label: 'High',
    resolution: 128,
    pressureIterations: 30,
    substeps: 1,
    steps: 112,
    shadowTaps: 3,
    renderScale: 1.0,
  },
  ultra: {
    label: 'Ultra',
    resolution: 160,
    pressureIterations: 40,
    substeps: 2,
    steps: 144,
    shadowTaps: 4,
    renderScale: 1.0,
  },
};

export const QUALITY_ORDER = ['low', 'medium', 'high', 'ultra'];
