/**
 * Unreal Engine 5 Niagara Fluids (Grid3D_Gas + Grid2D_ShallowWater + Grid3D_FLIP)
 * & EmberGen inspired presets, choreographed sequences, and default parameters.
 */

export const RESOLUTION_OPTIONS = [
  { value: 16, label: '16³  (4.1K Voxels — Ultra-Low GPU / Potato)', tilesX: 4, tilesY: 4 },
  { value: 24, label: '24³  (13.8K Voxels — Low-End GPU / Integrated)', tilesX: 6, tilesY: 4 },
  { value: 32, label: '32³  (32.7K Voxels — Stylized / Fast)', tilesX: 8, tilesY: 4 },
  { value: 48, label: '48³  (110.6K Voxels — Balanced)', tilesX: 8, tilesY: 6 },
  { value: 64, label: '64³  (262.1K Voxels — UE5 Niagara Default)', tilesX: 8, tilesY: 8 },
  { value: 96, label: '96³  (884.7K Voxels — High Detail Pyro/Hydro)', tilesX: 12, tilesY: 8 },
  { value: 128, label: '128³ (2.10M Voxels — Ultra Cinema Grid)', tilesX: 16, tilesY: 8 },
];

export const DEBUG_CHANNELS = [
  { id: 0, label: 'Combined Lit Volumetric (Pyro / Liquid PBR)' },
  { id: 1, label: 'Voxelized DDA Cubes (Discrete Voxel Grid)' },
  { id: 2, label: 'Primary Density ρ / Liquid Fraction φ(x,y,z)' },
  { id: 3, label: 'Temperature T / Whitewater Foam Field F(x,y,z)' },
  { id: 4, label: 'Fuel Core f / Surface Adhesion Film A(x,y,z)' },
  { id: 5, label: '3D Velocity Vectors u(x,y,z)' },
  { id: 6, label: 'Vorticity / Curl Magnitude |∇×u|' },
  { id: 7, label: 'Poisson Pressure & Irradiance p(x,y,z)' },
  { id: 8, label: '3D Grid Cross-Section Slice Inspector' },
];

export const COLOR_PALETTES = [
  { id: 0, label: 'Physical Planckian Blackbody (UE5 Pyro)' },
  { id: 1, label: 'Cinema Napalm / Rich Hydrocarbon' },
  { id: 2, label: 'Thermobaric White-Hot Ordnance' },
  { id: 3, label: 'Wildfire / Copper Emerald Flame' },
  { id: 4, label: 'Cherenkov Blue Plasma Core' },
  { id: 5, label: 'Arcane Void Magenta / Corrupt Pyro' },
  { id: 6, label: '🌊 Crystal Ocean Water + Whitewater Foam (Hydro)' },
  { id: 7, label: '🍫 Rich Melted Belgian Chocolate (Viscous Gloss)' },
  { id: 8, label: '🚜 Thick Off-Road Wet Mud & Clay (Adhesive)' },
  { id: 9, label: '🧪 Bioluminescent Radioactive Slime / Acid' },
];

export const OBSTACLE_TYPES = [
  { id: 0, label: 'None (Unobstructed Domain)' },
  { id: 1, label: '⚽ Moving / Interactive Sphere (Ball)' },
  { id: 2, label: '🏛️ Vertical Bridge Pier / Pillar' },
  { id: 3, label: '🛢️ Horizontal Cylinder / Submerged Pipe' },
  { id: 4, label: '🧱 Deflector Slab / Breakwater Wall' },
  { id: 5, label: '🛞 Spinning Off-Road Treaded Tire' },
];

export const WAVE_MODES = [
  { id: 0, label: 'Calm Pool (Collider Wakes & Splashes Only)' },
  { id: 1, label: 'Ocean Swell / Rolling Shallow Waves' },
  { id: 2, label: '🌊 Pipeline Surfing Wave (Overturning Barrel / Tube)' },
];

export const HYDRO_SCENES = [
  { id: 0, label: 'Open Pool (3D Liquid Volume)' },
  { id: 1, label: '🧱 Dam Breaker (Raised Water Column)' },
];

export const ATLAS_MINIMAP_FIELDS = [
  { id: 0, label: 'State Atlas (Pyro: R=Smoke G=Temp / Hydro: R=Liq G=Foam B=Adhesion)' },
  { id: 1, label: 'Velocity Atlas (RGB: Vx, Vy, Vz)' },
  { id: 2, label: 'Vorticity Curl Atlas (|∇×u|)' },
  { id: 3, label: 'Pressure & 3D Irradiance Atlas' },
];

export function createDefaultParams() {
  return {
    // Domain Solver Mode: 0 = Pyro (Fire/Smoke/Gas), 1 = Hydro (Volumetric 3D Liquid VOF)
    simMode: 0,

    // Grid & Solver
    gridResolution: 64,
    pressureIterations: 22,
    timeScale: 1.0,
    paused: false,
    macCormackAdvection: true,
    enclosedBox: false,
    voxelQuantization: 0.0, // 0 = smooth trilinear, 1 = discrete nearest voxel
    autoGpuGovernor: false, // Automatically adjusts steps/scale on low-end GPUs

    // World-Space Domain Bounds & Dynamic Expansion
    boundsWidth: 1.85,      // Horizontal X/Z domain width in world units (1.0 to 4.0)
    boundsHeight: 2.10,     // Vertical Y domain height in world units (1.0 to 4.0)
    dynamicBounds: true,    // Automatically expand domain bounds when explosions/splashes surge
    dynamicBoundsMax: 1.55, // Max dynamic multiplier during active blasts

    // Interactive Viewport Tool Mode
    interactionMode: 'orbit', // 'orbit' | 'flamethrower' | 'detonate'
    autoTurntable: false,

    // Pyro / Gas Fluid Physics
    vorticityConfinement: 7.8,
    buoyancy: 5.8,
    smokeWeight: 1.15,
    burnRate: 1.85,
    burnHeat: 2.6,
    sootGeneration: 1.55,
    combustionExpansion: 4.4,
    coolingRate: 1.35,
    smokeDissipation: 0.18,
    velocityDamping: 0.07,
    turbulenceStrength: 3.5,
    turbulenceScale: 3.8,
    windX: 0.22,
    windZ: 0.0,

    // Hydro / Volumetric 3D Liquid & Viscous Fluid Physics
    hydroScene: 0,            // 0 = open pool, 1 = raised dam-break column
    damGateX: 0.36,           // Initial dam face X position in normalized volume coordinates
    waterPoolLevel: 0.25,     // Base liquid fill height for pool/mud/chocolate (0.08 to 0.55)
    liquidGravity: 9.8,       // Downward gravity restoring splashes into pool
    liquidViscosity: 0.04,    // 0.02 = Water, 0.55 = Thick Mud, 0.80 = Melted Chocolate
    surfaceAdhesion: 0.65,    // Surface Wetting / Adhesion (sticks & climbs spinning tire / ball)
    surfaceTension: 0.52,     // Capillary cohesion pulling splashes into droplets, sheets & tendrils
    foamGeneration: 1.45,     // Whitewater foam & bubble generation on crests & wakes
    foamDissipation: 0.42,    // Foam longevity on the water surface
    splashEnergy: 1.50,       // Upward & rooster-tail splash intensity from tire/ball/wave
    waveMode: 0,              // 0 = Calm/Wake, 1 = Swell, 2 = Overturning Surfing Barrel Wave
    waveHeight: 0.48,         // Amplitude of waves / surfing tube
    waveSpeed: 1.35,          // Wave celerity / travel speed
    liquidSpecular: 1.35,     // Wet specular glossiness
    causticsIntensity: 0.70,  // Underwater refractive solar caustics on floor

    // Continuous Emitter (Fire Plume in Pyro / Fountain Jet in Hydro)
    emitterEnabled: true,
    emitterRate: 1.0,
    emitterRadius: 0.10,
    emitterHeight: 0.07,
    emitterPosY: 0.76,       // Hydro overhead pour height (Pyro uses emitterHeight as nozzle base)
    emitterUpwardVelocity: 3.2,
    emitterSwirl: 1.2,
    emitterTemperature: 3.5,
    emitterFuel: 2.8,
    emitterSmoke: 1.4,

    // Detonation / Explosion (Pyro) or Depth-Charge Crown Splash (Hydro)
    blastStrength: 9.8,
    blastRadius: 0.18,
    blastTemperature: 5.4,
    blastFuel: 4.6,
    blastSmoke: 2.6,
    blastLobes: 6.0,
    shrapnelEnabled: true,

    // Volumetric Raymarching & Shading
    renderChannel: 0,
    colorPalette: 0,
    renderScale: 1.0,
    raymarchSteps: 96,
    shadowSteps: 6,
    densityExtinction: 18.5,
    smokeAlbedo: 0.22,
    shadowDensity: 11.5,
    fireIntensity: 5.6,
    temperatureScale: 1.15,
    internalScattering: 2.5,
    phaseAnisotropy: 0.38,
    ambientIntensity: 0.35,
    sunIntensity: 2.2,
    sunAzimuth: 42.0,
    sunElevation: 52.0,
    exposure: 1.25,
    bloomIntensity: 0.55,
    godRaysIntensity: 0.45,
    shockwaveStrength: 1.0,

    // Slice Inspector
    sliceAxis: 2, // 0=X, 1=Y, 2=Z
    slicePosition: 0.5,

    // Voxelized Obstacle Collider & Kinematic Tire/Ball Motion
    obstacleType: 0,
    obstacleX: 0.5,
    obstacleY: 0.26,
    obstacleZ: 0.5,
    obstacleRadius: 0.16,
    colliderAutoMove: true,
    colliderSpeed: 1.25,

    // Viewport Overlays & Diagnostics
    showBoundingBox: true,
    showVoxelGridLines: true,
    showActiveVoxelCells: false,
    showFloorGrid: true,
    showEmbers: true,
    emberCount: 550,
    emberSize: 1.0,
    emberIntensity: 1.4,
    emberLifetime: 1.0,
    emberAshiness: 0.0, // 0 = hot orange fireflies, 1 = cool grey ash motes
    showAtlasMinimap: true,
    atlasMinimapField: 0,
  };
}

export const PRESETS = {
  hydro_dam_breaker: {
    name: '🧱 3D Dam Breaker (Water Column)',
    description: 'A raised 3D water column collapses through the open domain, forming a volumetric surge, rolling front, splash sheet, droplets, and foam in every direction.',
    triggerExplosionOnLoad: false,
    params: {
      simMode: 1,
      hydroScene: 1,
      gridResolution: 64,
      pressureIterations: 16,
      boundsWidth: 2.75,
      boundsHeight: 1.90,
      dynamicBounds: false,
      waterPoolLevel: 0.58,
      damGateX: 0.34,
      liquidGravity: 9.8,
      liquidViscosity: 0.035,
      surfaceAdhesion: 0.18,
      surfaceTension: 0.44,
      foamGeneration: 1.85,
      foamDissipation: 0.34,
      splashEnergy: 1.85,
      waveMode: 0,
      waveHeight: 0.10,
      waveSpeed: 1.0,
      liquidSpecular: 1.35,
      causticsIntensity: 0.72,
      emitterEnabled: false,
      obstacleType: 0,
      showEmbers: false,
      showVoxelGridLines: false,
      showActiveVoxelCells: false,
    },
  },

  hydro_tire_splash: {
    name: '🛞 Tire in Volumetric Water (Splash + Foam)',
    description: 'Spinning off-road treaded tire plowing through a voxel liquid volume—throwing 3D rooster-tail splashes, wakes, whitewater foam, and surface adhesion.',
    triggerExplosionOnLoad: false,
    params: {
      simMode: 1,
      hydroScene: 0,
      gridResolution: 64,
      pressureIterations: 16,
      boundsWidth: 2.35,
      boundsHeight: 1.75,
      dynamicBounds: true,
      voxelQuantization: 0.0,
      renderChannel: 0,
      colorPalette: 6,
      waterPoolLevel: 0.24,
      liquidGravity: 9.8,
      liquidViscosity: 0.03,
      surfaceAdhesion: 0.65,
      surfaceTension: 0.52,
      foamGeneration: 1.65,
      foamDissipation: 0.38,
      splashEnergy: 1.65,
      waveMode: 0,
      waveHeight: 0.22,
      waveSpeed: 1.25,
      liquidSpecular: 1.45,
      causticsIntensity: 0.80,
      emitterEnabled: false,
      obstacleType: 5, // Spinning Off-Road Treaded Tire
      obstacleX: 0.5,
      obstacleY: 0.21,
      obstacleZ: 0.5,
      obstacleRadius: 0.17,
      colliderAutoMove: true,
      colliderSpeed: 1.35,
      densityExtinction: 22.0,
      shadowDensity: 13.5,
      sunIntensity: 2.5,
      sunElevation: 56.0,
      godRaysIntensity: 0.40,
      showEmbers: false,
      showVoxelGridLines: false,
      showActiveVoxelCells: false,
    },
  },

  hydro_surfing_wave: {
    name: '🌊 Surfing Barrel Wave (Pipeline Tube)',
    description: 'Overturning 3D plunging surfing wave that pitches forward into a hollow tube/barrel with crashing lip, churning whitewater foam, and volumetric shadows.',
    triggerExplosionOnLoad: false,
    params: {
      simMode: 1,
      hydroScene: 0,
      gridResolution: 64,
      pressureIterations: 16,
      boundsWidth: 2.50,
      boundsHeight: 1.85,
      dynamicBounds: true,
      voxelQuantization: 0.0,
      renderChannel: 0,
      colorPalette: 6,
      waterPoolLevel: 0.22,
      liquidGravity: 9.5,
      liquidViscosity: 0.025,
      surfaceAdhesion: 0.45,
      surfaceTension: 0.58,
      foamGeneration: 1.85,
      foamDissipation: 0.35,
      splashEnergy: 1.70,
      waveMode: 2, // Pipeline Surfing Barrel Wave
      waveHeight: 0.68,
      waveSpeed: 1.35,
      liquidSpecular: 1.50,
      causticsIntensity: 0.85,
      emitterEnabled: false,
      obstacleType: 0,
      colliderAutoMove: false,
      densityExtinction: 22.5,
      shadowDensity: 14.0,
      sunIntensity: 2.6,
      sunAzimuth: 28.0,
      sunElevation: 48.0,
      godRaysIntensity: 0.55,
      showEmbers: false,
      showVoxelGridLines: false,
      showActiveVoxelCells: false,
    },
  },

  hydro_ball_splash: {
    name: '⚽ Moving Ball in Water (Crown Splash)',
    description: 'Slaloming & plunging sphere through a voxel liquid volume, creating 3D crown splashes, surface-tension sheets clinging to the ball, and foam trails.',
    triggerExplosionOnLoad: true,
    params: {
      simMode: 1,
      hydroScene: 0,
      gridResolution: 64,
      pressureIterations: 16,
      boundsWidth: 2.30,
      boundsHeight: 1.75,
      dynamicBounds: true,
      voxelQuantization: 0.0,
      renderChannel: 0,
      colorPalette: 6,
      waterPoolLevel: 0.25,
      liquidGravity: 9.6,
      liquidViscosity: 0.03,
      surfaceAdhesion: 0.72,
      surfaceTension: 0.56,
      foamGeneration: 1.55,
      foamDissipation: 0.40,
      splashEnergy: 1.60,
      waveMode: 1,
      waveHeight: 0.24,
      waveSpeed: 1.20,
      liquidSpecular: 1.45,
      causticsIntensity: 0.78,
      emitterEnabled: false,
      obstacleType: 1, // Moving Sphere / Ball
      obstacleX: 0.5,
      obstacleY: 0.22,
      obstacleZ: 0.5,
      obstacleRadius: 0.15,
      colliderAutoMove: true,
      colliderSpeed: 1.30,
      densityExtinction: 22.0,
      shadowDensity: 13.0,
      sunIntensity: 2.5,
      showEmbers: false,
      showVoxelGridLines: false,
      showActiveVoxelCells: false,
    },
  },

  liquid_melted_chocolate: {
    name: '🍫 Melted Chocolate + Spinning Wheel',
    description: 'High-viscosity glossy Belgian chocolate with strong Surface Adhesion—clings to the rotating tire, stretches into thick ribbons, and folds into creamy swirls.',
    triggerExplosionOnLoad: false,
    params: {
      simMode: 1,
      hydroScene: 0,
      gridResolution: 64,
      pressureIterations: 16,
      boundsWidth: 2.15,
      boundsHeight: 1.70,
      dynamicBounds: true,
      voxelQuantization: 0.0,
      renderChannel: 0,
      colorPalette: 7, // Melted Belgian Chocolate
      waterPoolLevel: 0.26,
      liquidGravity: 8.2,
      liquidViscosity: 0.78,
      surfaceAdhesion: 1.25, // High surface wetting / cling!
      surfaceTension: 0.88,  // Strong cohesive ribbons
      foamGeneration: 1.10,  // Creamy light-cocoa swirls
      foamDissipation: 0.22,
      splashEnergy: 1.35,
      waveMode: 0,
      waveHeight: 0.20,
      waveSpeed: 0.85,
      liquidSpecular: 1.65,
      causticsIntensity: 0.15,
      emitterEnabled: true, // Overhead chocolate pour stream!
      emitterRate: 1.15,
      emitterRadius: 0.09,
      emitterPosY: 0.75,
       obstacleType: 5, // Spinning Tire
      obstacleX: 0.5,
      obstacleY: 0.23,
      obstacleZ: 0.5,
      obstacleRadius: 0.17,
      colliderAutoMove: true,
      colliderSpeed: 0.95,
      densityExtinction: 26.0,
      shadowDensity: 15.0,
      sunIntensity: 2.6,
      sunElevation: 54.0,
      godRaysIntensity: 0.25,
      showEmbers: false,
      showVoxelGridLines: false,
      showActiveVoxelCells: false,
    },
  },

  liquid_thick_mud: {
    name: '🚜 Off-Road Tire in Thick Mud Bog',
    description: 'Spinning off-road tire churning through heavy wet mud & clay—mud coats the tire treads via adhesion and flings thick viscous splatters with deep shadows.',
    triggerExplosionOnLoad: false,
    params: {
      simMode: 1,
      hydroScene: 0,
      gridResolution: 64,
      pressureIterations: 16,
      boundsWidth: 2.25,
      boundsHeight: 1.75,
      dynamicBounds: true,
      voxelQuantization: 0.0,
      renderChannel: 0,
      colorPalette: 8, // Thick Wet Mud & Clay
      waterPoolLevel: 0.25,
      liquidGravity: 9.2,
      liquidViscosity: 0.56,
      surfaceAdhesion: 1.05, // Mud sticks heavily to tire treads!
      surfaceTension: 0.72,
      foamGeneration: 1.30,
      foamDissipation: 0.28,
      splashEnergy: 1.75,
      waveMode: 0,
      waveHeight: 0.22,
      waveSpeed: 0.95,
      liquidSpecular: 1.25,
      causticsIntensity: 0.20,
      emitterEnabled: false,
      obstacleType: 5, // Spinning Off-Road Tire
      obstacleX: 0.5,
      obstacleY: 0.21,
      obstacleZ: 0.5,
      obstacleRadius: 0.18,
      colliderAutoMove: true,
      colliderSpeed: 1.40,
      densityExtinction: 25.0,
      shadowDensity: 15.0,
      sunIntensity: 2.4,
      sunElevation: 52.0,
      godRaysIntensity: 0.30,
      showEmbers: false,
      showVoxelGridLines: false,
      showActiveVoxelCells: false,
    },
  },

  ue5_pyro_default: {
    name: '🔥 UE5 Niagara Pyro Plume + Blast',
    description: 'Balanced hydrocarbon fireball with dynamic expanding bounds, ballistic shrapnel trails, and rolling dark soot.',
    triggerExplosionOnLoad: true,
    params: {
      simMode: 0,
      gridResolution: 64,
      boundsWidth: 1.85,
      boundsHeight: 2.10,
      dynamicBounds: true,
      shrapnelEnabled: true,
      voxelQuantization: 0.0,
      renderChannel: 0,
      colorPalette: 0,
      vorticityConfinement: 7.8,
      buoyancy: 5.8,
      smokeWeight: 1.15,
      burnRate: 1.85,
      burnHeat: 2.6,
      sootGeneration: 1.55,
      combustionExpansion: 4.4,
      coolingRate: 1.35,
      smokeDissipation: 0.18,
      turbulenceStrength: 3.5,
      emitterEnabled: true,
      emitterRate: 1.0,
      emitterRadius: 0.10,
      emitterUpwardVelocity: 3.2,
      emitterSwirl: 1.2,
      emitterTemperature: 3.5,
      emitterFuel: 2.8,
      emitterSmoke: 1.4,
      densityExtinction: 18.5,
      smokeAlbedo: 0.22,
      fireIntensity: 5.6,
      internalScattering: 2.5,
      godRaysIntensity: 0.45,
      obstacleType: 0,
      showEmbers: true,
      showActiveVoxelCells: false,
    },
  },

  shrapnel_airburst: {
    name: '☄️ Ordnance Shrapnel Airburst',
    description: 'High-explosive airburst ejecting 6 burning ballistic shrapnel fragments that arc through the 3D volume leaving smoke streamers.',
    triggerExplosionOnLoad: true,
    params: {
      simMode: 0,
      boundsWidth: 2.45,
      boundsHeight: 2.55,
      dynamicBounds: true,
      shrapnelEnabled: true,
      emitterEnabled: false,
      colorPalette: 0,
      vorticityConfinement: 8.8,
      buoyancy: 5.2,
      smokeDissipation: 0.12,
      blastStrength: 11.5,
      blastRadius: 0.19,
      blastTemperature: 6.2,
      godRaysIntensity: 0.65,
      obstacleType: 0,
      showEmbers: true,
      showActiveVoxelCells: false,
    },
  },

  megaton_open_bounds: {
    name: '💥 Megaton Wide-Bounds Blast',
    description: 'Extra-large 3.0x simulation bounds with dynamic surge expansion so massive explosions and salvos have full room to mushroom.',
    triggerExplosionOnLoad: true,
    params: {
      simMode: 0,
      boundsWidth: 2.85,
      boundsHeight: 2.95,
      dynamicBounds: true,
      shrapnelEnabled: true,
      voxelQuantization: 0.0,
      renderChannel: 0,
      colorPalette: 0,
      vorticityConfinement: 9.2,
      buoyancy: 6.2,
      smokeWeight: 1.2,
      burnRate: 1.75,
      burnHeat: 3.0,
      sootGeneration: 1.9,
      combustionExpansion: 5.8,
      coolingRate: 1.2,
      smokeDissipation: 0.11,
      turbulenceStrength: 4.5,
      emitterEnabled: false,
      blastStrength: 13.5,
      blastRadius: 0.18,
      blastTemperature: 6.5,
      blastFuel: 5.4,
      blastSmoke: 3.0,
      densityExtinction: 20.0,
      smokeAlbedo: 0.26,
      fireIntensity: 6.5,
      internalScattering: 3.0,
      obstacleType: 0,
      showEmbers: true,
      showActiveVoxelCells: false,
    },
  },

  low_gpu_performance: {
    name: '⚡ Low-End GPU Fast Mode (24³)',
    description: 'Ultra-lightweight 24³ voxel grid (13.8K voxels) + 56 raymarch steps for silky-smooth 60+ FPS on integrated/mobile GPUs.',
    triggerExplosionOnLoad: true,
    params: {
      gridResolution: 24,
      boundsWidth: 2.0,
      boundsHeight: 2.2,
      dynamicBounds: true,
      pressureIterations: 14,
      raymarchSteps: 56,
      shadowSteps: 4,
      renderScale: 0.85,
      voxelQuantization: 0.0,
      renderChannel: 0,
      vorticityConfinement: 8.5,
      buoyancy: 6.0,
      showActiveVoxelCells: false,
    },
  },

  tactical_ordnance: {
    name: '🧨 Tactical C4 / HE Blast Wave',
    description: 'High-explosive shockwave detonation with rapid divergence expansion, blinding flash core, and billowing dust/soot cloud.',
    triggerExplosionOnLoad: true,
    params: {
      simMode: 0,
      boundsWidth: 2.25,
      boundsHeight: 2.40,
      dynamicBounds: true,
      shrapnelEnabled: true,
      voxelQuantization: 0.0,
      renderChannel: 0,
      colorPalette: 2,
      vorticityConfinement: 9.2,
      buoyancy: 4.6,
      smokeWeight: 1.3,
      burnRate: 2.6,
      burnHeat: 3.2,
      sootGeneration: 2.1,
      combustionExpansion: 6.5,
      coolingRate: 1.75,
      smokeDissipation: 0.14,
      turbulenceStrength: 4.8,
      emitterEnabled: false,
      blastStrength: 12.5,
      blastRadius: 0.20,
      blastTemperature: 6.4,
      blastFuel: 5.2,
      blastSmoke: 3.2,
      densityExtinction: 22.0,
      smokeAlbedo: 0.34,
      fireIntensity: 6.8,
      internalScattering: 3.1,
      obstacleType: 0,
      showEmbers: true,
      showActiveVoxelCells: false,
    },
  },

  oil_well_inferno: {
    name: '🛢️ Raging Oil Well Inferno',
    description: 'High-velocity pressurized fuel blowout generating a roaring flame column and dense carbonaceous black smoke.',
    triggerExplosionOnLoad: false,
    params: {
      simMode: 0,
      boundsWidth: 1.9,
      boundsHeight: 2.4,
      dynamicBounds: true,
      voxelQuantization: 0.0,
      renderChannel: 0,
      colorPalette: 1,
      vorticityConfinement: 8.8,
      buoyancy: 7.2,
      smokeWeight: 1.4,
      burnRate: 1.6,
      burnHeat: 3.1,
      sootGeneration: 2.2,
      combustionExpansion: 3.4,
      coolingRate: 1.15,
      smokeDissipation: 0.22,
      turbulenceStrength: 4.2,
      windX: 0.65,
      emitterEnabled: true,
      emitterRate: 1.45,
      emitterRadius: 0.11,
      emitterUpwardVelocity: 5.4,
      emitterSwirl: 1.8,
      emitterTemperature: 4.2,
      emitterFuel: 3.6,
      emitterSmoke: 1.9,
      densityExtinction: 24.0,
      smokeAlbedo: 0.12,
      fireIntensity: 6.0,
      internalScattering: 2.8,
      obstacleType: 0,
      showEmbers: true,
      showActiveVoxelCells: false,
    },
  },

  obstacle_deflection: {
    name: '🧱 Voxel Collider Flow Deflection',
    description: 'Demonstrates a 3D solid sphere collider inside the Eulerian grid—fire and smoke split and curl around the obstacle.',
    triggerExplosionOnLoad: true,
    params: {
      simMode: 0,
      boundsWidth: 1.85,
      boundsHeight: 2.10,
      colorPalette: 0,
      vorticityConfinement: 8.4,
      buoyancy: 6.4,
      burnRate: 1.75,
      combustionExpansion: 3.8,
      coolingRate: 1.2,
      smokeDissipation: 0.18,
      emitterEnabled: true,
      emitterRate: 1.25,
      emitterRadius: 0.11,
      emitterUpwardVelocity: 4.6,
      obstacleType: 1,
      obstacleX: 0.5,
      obstacleY: 0.42,
      obstacleZ: 0.5,
      obstacleRadius: 0.16,
      showActiveVoxelCells: false,
    },
  },

  wildfire_tornado: {
    name: '🌪️ Fire Tornado / Alchemical Vortex',
    description: 'High-swirl fire tornado with copper-emerald blackbody radiation and intense rotational vorticity.',
    triggerExplosionOnLoad: true,
    params: {
      simMode: 0,
      boundsWidth: 1.9,
      boundsHeight: 2.3,
      colorPalette: 3,
      vorticityConfinement: 9.5,
      buoyancy: 6.8,
      burnRate: 1.7,
      combustionExpansion: 3.5,
      coolingRate: 1.25,
      smokeDissipation: 0.20,
      turbulenceStrength: 3.8,
      emitterEnabled: true,
      emitterRate: 1.3,
      emitterRadius: 0.12,
      emitterUpwardVelocity: 4.2,
      emitterSwirl: 5.5,
      emitterTemperature: 3.9,
      emitterFuel: 3.2,
      obstacleType: 0,
      showActiveVoxelCells: false,
    },
  },

  ashfall_motes: {
    name: '🌫️ Ashfall / Grey Fireflies',
    description: 'A cooling afterburn cloud with dense grey ash motes instead of orange sparks—use the ember sliders to tune size, brightness, lifetime, and ashiness.',
    triggerExplosionOnLoad: true,
    params: {
      simMode: 0,
      emitterEnabled: false,
      blastStrength: 7.0,
      blastRadius: 0.20,
      blastTemperature: 2.4,
      blastFuel: 1.2,
      blastSmoke: 3.8,
      colorPalette: 1,
      smokeDissipation: 0.08,
      showEmbers: true,
      emberCount: 900,
      emberSize: 1.25,
      emberIntensity: 0.95,
      emberLifetime: 1.65,
      emberAshiness: 1.0,
      showActiveVoxelCells: false,
    },
  },

  voxelized_stylized: {
    name: '🧊 Voxelized Stylized Grid (DDA)',
    description: 'Explicit voxelized resolution look showing discrete 3D grid cells with quantized volumetric shading.',
    triggerExplosionOnLoad: true,
    params: {
      voxelQuantization: 0.88,
      renderChannel: 1,
      vorticityConfinement: 8.0,
      showActiveVoxelCells: true,
    },
  },
};
